### ISSUE TITLE
vendor/bin/selenium-server-standalone script does not work with parameters in 3.0.1

### ISSUE THREAD

**Issue by asgrim** [sveneisenschmidt/selenium-server-standalone#17]
```bash
$ vendor/bin/selenium-server-standalone -Dwebdriver.gecko.driver=/opt/selenium/geckodriver
Exception in thread "main" com.beust.jcommander.ParameterException: Unknown option: -Dwebdriver.gecko.driver=/opt/selenium/geckodriver
	at com.beust.jcommander.JCommander.parseValues(JCommander.java:742)
	at com.beust.jcommander.JCommander.parse(JCommander.java:282)
	at com.beust.jcommander.JCommander.parse(JCommander.java:265)
	at com.beust.jcommander.JCommander.<init>(JCommander.java:210)
	at org.openqa.grid.selenium.GridLauncherV3$1.setConfiguration(GridLauncherV3.java:219)
	at org.openqa.grid.selenium.GridLauncherV3.buildLauncher(GridLauncherV3.java:147)
	at org.openqa.grid.selenium.GridLauncherV3.main(GridLauncherV3.java:73)
$
```

It appears the options now need to come beforehand, e.g.:

```
$ /usr/lib/jvm/java-8-openjdk-amd64/jre/bin/java -jar -Dwebdriver.chrome.driver=/opt/selenium/chromedriver vendor/se/selenium-server-standalone/bin/selenium-server-standalone.jar
```

**Comment by asgrim** [comment]
Updating the script like so:

```diff
- exec java -jar "${SELF_PATH}.jar" "$@"
+ exec java -jar "$@" "${SELF_PATH}.jar"
```

seems to work, but I'm not sure what else might break. I'll open a PR anyway.

**Comment by asgrim** [comment]
Ah, things like `-port 4445` break, so maybe not such a good idea. I think the workaround here is to make sure `chromedriver` are in the path so the options aren't required, not sure how else to solve this nicely without parsing the parameters in the script and splitting out `-D` params to before the `.jar` file in the command.

**Comment by sveneisenschmidt** [comment]
Thank you a lot for finding this out. So maybe then we have to remove support for the bin file or find a better way in handling driver support. @javigomez You have a lot of experience with webdrivers. What do you think? 

At the end the bin file is just a proxy and I assume deprecrating it is an option before everyone updates to 3.0.1. @asgrim How come you did update so fast, what was your version inside composer?

**Comment by sveneisenschmidt** [comment]
@asgrim What geckodriver version are you using? I'd like to setup a test case in 'tests/SE/SeleniumServerStandalone/Test/ExecutableTest.php'.

**Comment by asgrim** [comment]
@sveneisenshmidt I installed from Fresh, just starting a new Behat suite with it, so I didn't have unbounded constraints ;)

The `geckodriver` I'm using is the latest from https://github.com/mozilla/geckodriver/releases - which is currently 0.11.1. It's platform dependent, but I grabbed the `linux64` flavour :)

**Comment by sveneisenschmidt** [comment]
@asgrim I won't have any time to upgrade the bin file in the near future to provide a fix so I rather choose to remove the bash bin file for  >=3.0.1. Any objections from user perspective?

**Comment by asgrim** [comment]
I don't think it's necessary to remove it. Just consider it a "known bug" that whatever web driver user requires must be in `PATH` when using the script. I'd prefer to keep the script and use that workaround personally :)

**Comment by asgrim** [comment]
Also, that'd be a BC break, if you're following semver, although I appreciate the versions just follow selenium versions anyways :)

**Comment by sveneisenschmidt** [comment]
@asgrim If we are introducing a new major version we can have a breaking change right?

**Comment by asgrim** [comment]
Sure; but you'd lose the parity between this package and the real selenium-server-standalone version, which I'd argue is one of the more useful aspects.

**Comment by sveneisenschmidt** [comment]
@asgrim Maybe I miss understood you. I think we keep parity between version numbers but only introduce a BC break in our additional code. Although I am fine with introducing the issue as a known bug and move forward. 

PS: I pulled v3.0.1 stable of this package and did a pre release with v3.0.1-beta1 until a decision on this issue is found. I want to strongly gather opinions before making a decision.

**Comment by asgrim** [comment]
I think that's a little extreme; once a release is made, it shouldn't be removed really :s clients may already depend on that version (and indeed, our application does)...

As for the issue; as I said, it's likely just a known issue; it's not possible to pass the `-Dwebdriver.whatever.driver` options, but the workaround (ensuring the webdriver is in `PATH`) is perfectly acceptable. It's almost a non-issue really (it's less convenient to have to provide the path to the webdriver every time anyway).

**Comment by sveneisenschmidt** [comment]
@asgrim I've documented the new behaviour, any objections? PR #19

**Comment by sveneisenschmidt** [comment]
Closed with #19. @asgrim Big thanks to you. New release is under way.

**Comment by asgrim** [comment]
Thanks @sveneisenschmidt :+1:

**Comment by sveneisenschmidt** [comment]
@asgrim Are you fancy becoming a collaborator?

**Comment by sveneisenschmidt** [comment]
@asgrim Done. With your next potential PR/update please add yourself as an author to the composer.json file. Thank you for being part of this package.

**Comment by asgrim** [comment]
Thanks! :)

**Comment by fezfez** [comment]
Adding a check if firefox or chrome is in $path, would be very helpfull.

Sample if none of this two are found : 

```
<alert>No driver found, consider adding firefox, chrome or IE to your $PATH variable environnement.</alert>

(selenium start)
```

Sample if firefox found
```
<info>Only firefox would be avaible as driver, if you want have more of more driver, add those to your $PATH variable environnement.</info>

(selenium start)
```

I can make a PR if it sound interessting to you

**Comment by fezfez** [comment]
ping @sveneisenschmidt

**Comment by sveneisenschmidt** [comment]
Hello @fezfez,

I am pn vacation this week. I like your idea. Let us have a chat about it when I am back.

**Comment by asgrim** [comment]
@fezfez fwiw, this seems like a reasonable approach imo

**Comment by sveneisenschmidt** [comment]
@fezfez Are you fancy working on this? I think we think it is a good idea to have this. Especially because of issue #17.

**Comment by fezfez** [comment]
@sveneisenschmidt : I start :)

**Comment by sveneisenschmidt** [comment]
@fezfez What about having a nice checklist?

```bash
Webdriver status:
-----------------

✓ chrome (found in PATH)
×  gecko
×  ...
×  ...
```

For a full list plase see https://github.com/joomla-projects/selenium-server-standalone/tree/master/bin/webdrivers. Some months ago I had contact with the maintainers and I porposed merging both projects so your feature idea would be a very good enhancement.

**Comment by fezfez** [comment]
Good idea, i look into

**Comment by fezfez** [comment]
I found a way more efficient strategy but i need more time than expected.
I keep you up to date
