### ISSUE TITLE
Racing condition between Selenium Server and ChromeDriver

### ISSUE THREAD

**Issue by SzabKel** [sveneisenschmidt/selenium-server-standalone#32]
Main issue: ChromeDriver won't delete it's scoped_dir****_***** folders from Windows's Temporary files.

[It was supposed to be fixed a few times already.](https://stackoverflow.com/questions/43289035/chromedriver-not-deleting-scoped-dir-in-temp-folder-after-test-is-complete), but I am still struggling with this, when I am using `selenium-server` version `3.6.0` (and a few versions before this one too) with ChromeDriver 2.33 on a Windows 7 x64 virtual machine. The directories just keep piling up (each around 5MB) and after a day or two it slows down the system. I saw this issue mentioned with Firefox's driver too.

As much as I can see, sometimes when a browser closes a scoped_dir folder gets deleted, but most of the time it won't. I tried to use a ps1 script to manually delete the files ([source](https://paste.ubuntu.com/25766373/), mentioned [here](https://sqa.stackexchange.com/questions/26675/chromedriver-not-deleting-scoped-dir-in-temp-folder-after-test-is-complete/27070)), but It just cannot delete them until I shutdown `selenium-server`. For me, It looks like Chrome and selenium-server keep each other from deleting the files.

Please tell me, what information should I share to help this issue resolved.

Until then:

- I am using Java 1.8 to connect to the server
-  I start the selenium server with simply calling `java -jar selenium-server.jar`
- My test cases require lot's of browser starting and stopping, but I close them every time with a `driver.quit()` in a `try-catch-finally` structure.
- I tried using `driver.close()` before calling `driver.quit()`, but it just crashed with an already closed driver exception.

**Comment by asgrim** [comment]
Hi @SzabKel, sorry but this isn't the bug tracker for Selenium; this is just a composer package for PHP projects to download the Selenium JAR.

I think (but not 100% sure) the right place for your issue is over at https://github.com/SeleniumHQ/selenium/issues

Thanks!
