### ISSUE TITLE
Problem of usage

### ISSUE THREAD

**Issue by espekkaya** [sveneisenschmidt/selenium-server-standalone#36]
Hello,
Sorry but I do not understand where I can write "$ bin/selenium-server-standalone". I run manually selenium-server-standalone on cmd prompt. By the way I developed php test script on phpstorm ide.

Thank you

**Comment by asgrim** [comment]
You run it in the command prompt, without the `$` (that indicates to the reader that the prompt is there, nothing more).

**Comment by espekkaya** [comment]
Thank you.

But when I run on command prompt I got an error.

`C:\xampp\htdocs\sample>bin/selenium-server-standalone
'bin' is not recognized as an internal or external command,
operable program or batch file.
`

**Comment by asgrim** [comment]
The instructions are designed for Linux, not Windows. You can run the JAR directly instead (I'd guess something like `java -jar bin/selenium-server-standalone.jar (your-params-here)`, but I don't use Windows so couldn't say for sure).
