### ISSUE TITLE
Can not find the Auther?

### ISSUE THREAD

**Issue by iqpkeq** [sveneisenschmidt/selenium-server-standalone#44]
hi. I want to know how to bulid The SourceCode Zip from the Code.?
i download the  code from git that Selenium of the offical site.but cann't export SourceCode Zip can linked!

Best Regards

**Comment by asgrim** [comment]
@iqpkeq not really sure what you're asking for here...? Are you asking about building Selenium itself from source? If so, you'd need to go to their repository. This is just a library to pull the JAR into a Composer package...

**Comment by iqpkeq** [comment]
@asgrim i'm meaning that i got  selenium-server-standalone.jar ;But i cann't find selenium-server-standalone-source.jar (maybe different name?) on the Office site.

**Comment by asgrim** [comment]
@iqpkeq Sorry, but this is not the repo for the actual code for `selenium-server-standalone`. You'd need to check on https://www.seleniumhq.org/ for where that is located. As I said, this library just redistributes the JAR in a Composer package for PHP users, we don't have any source code for it here.
